services:
  - type: web
    name: itu-m2-rest-api-spring-boot
    runtime: java
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17